### ISSUE TITLE
Internal server error on signin

### ISSUE THREAD

**Issue by create-upside** [23gate/23gate#2]
After i click sign in and allow access to "evm-hook" for oauth it redirects me to a ngrok link which is weird.. but i figured that i can login using my github id and secret filled in the env (of the backend) by refreshing the page in the /login/github. but even after i allow access there i am met with "Internal server error".

Backend logs this:
```
Caught error:
ValidationError [SequelizeValidationError]: notNull Violation: User.email cannot be null
    at InstanceValidator._validate (C:\Users\sudip\OneDrive\Desktop\new-work-folder\23gate\backend\node_modules\sequelize\lib\instance-validator.js:50:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async InstanceValidator._validateAndRunHooks (C:\Users\sudip\OneDrive\Desktop\new-work-folder\23gate\backend\node_modules\sequelize\lib\instance-validator.js:60:7)
    at async InstanceValidator.validate (C:\Users\sudip\OneDrive\Desktop\new-work-folder\23gate\backend\node_modules\sequelize\lib\instance-validator.js:54:12)
    at async User.save (C:\Users\sudip\OneDrive\Desktop\new-work-folder\23gate\backend\node_modules\sequelize\lib\model.js:2426:7)
    at async User.create (C:\Users\sudip\OneDrive\Desktop\new-work-folder\23gate\backend\node_modules\sequelize\lib\model.js:1362:12)
    at async User.findOrCreate (C:\Users\sudip\OneDrive\Desktop\new-work-folder\23gate\backend\node_modules\sequelize\lib\model.js:1422:25)
    at async Object.<anonymous> (file:///C:/Users/sudip/OneDrive/Desktop/new-work-folder/23gate/backend/index.mjs:96:3) {
  errors: [
    ValidationErrorItem {
      message: 'User.email cannot be null',
      type: 'notNull Violation',
      path: 'email',
      value: null,
      origin: 'CORE',
      instance: [User],
      validatorKey: 'is_null',
      validatorName: null,
      validatorArgs: []
    }
  ]
}
```

Any idea why this is happening please? Thanks

**Comment by Teriyaki229** [comment]
This is the ngrok link:
[merry-radically-pipefish.ngrok-free.app](https://merry-radically-pipefish.ngrok-free.app/login/github/callback?code=xxx)

**Comment by egorFiNE** [comment]
Somehow we don't receive email from github and we don't handle this error gracefully. yet.

**Comment by egorFiNE** [comment]
(ngrok link is weird, I cannot find it anywhere in the repo)

**Comment by create-upside** [comment]
> (ngrok link is weird, I cannot find it anywhere in the repo)

I think the ngrok link is the callback url in the "evm-hooks" repo. Which I am required to be authenticated with when I click the sign in button.

**Comment by Teriyaki229** [comment]
> Somehow we don't receive email from github and we don't handle this error gracefully. yet.

Why is this happening and how do you think I can resolve it...? My GitHub app I made and supplied the client id and secret in the backend have read email permissions.

**Comment by create-upside** [comment]
issue was due to me not having a public email.
